CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "user_code" varchar(255) UNIQUE,
  "email" varchar(255) UNIQUE,
  "password" varchar(255),
  "role" varchar(50) DEFAULT 'entrepreneur',
  "profile_image" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "domain" varchar(100),
  "short_description" varchar(255),
  "problem" text,
  "solution" text,
  "tech_stack" text,
  "team_type" varchar(50),
  "looking_for_cofounders" boolean DEFAULT false,
  "github_url" varchar(255),
  "demo_url" varchar(255),
  "stage" varchar(50) DEFAULT 'Idea',
  "funding_stage" varchar(50),
  "status" varchar(50) DEFAULT 'Pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "project_entrepreneurs" (
  "project_id" int REFERENCES "projects" ("id") ON DELETE CASCADE,
  "user_id" int REFERENCES "users" ("id") ON DELETE CASCADE,
  "role_in_project" varchar(50)
);

CREATE TABLE IF NOT EXISTS "workshops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "trainer_id" int REFERENCES "users" ("id") ON DELETE SET NULL,
  "schedule" timestamp,
  "capacity" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "workshop_attendance" (
  "workshop_id" int REFERENCES "workshops" ("id") ON DELETE CASCADE,
  "user_id" int REFERENCES "users" ("id") ON DELETE CASCADE,
  "attended_at" timestamp DEFAULT (now()),
  "feedback" text
);

CREATE TABLE IF NOT EXISTS "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "type" varchar(50),
  "description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "project_resources" (
  "project_id" int REFERENCES "projects" ("id") ON DELETE CASCADE,
  "resource_id" int REFERENCES "resources" ("id") ON DELETE CASCADE,
  "allocated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "funding_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" INT REFERENCES "projects" ("id") ON DELETE CASCADE,
  "investor_id" INT REFERENCES "users" ("id") ON DELETE SET NULL,
  "amount" DECIMAL(15,2),
  "status" VARCHAR(50) DEFAULT 'Pending',
  "funding_stage" VARCHAR(50),
  "description" TEXT,
  "reviewed_by" INT REFERENCES "users" ("id") ON DELETE SET NULL,
  "notes" TEXT,
  "reviewed_at" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_funding_project ON "funding_requests"("project_id");
CREATE INDEX IF NOT EXISTS idx_funding_status ON "funding_requests"("status");
CREATE INDEX IF NOT EXISTS idx_funding_stage ON "funding_requests"("funding_stage");
CREATE INDEX IF NOT EXISTS idx_funding_created ON "funding_requests"("created_at");

CREATE TABLE IF NOT EXISTS "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL,
  PRIMARY KEY ("sid")
);
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");